/**
 * Selectors Module
 *
 * Exports all selectors for extracting and deriving data from state.
 * All selectors are pure functions compatible with any state management library.
 *
 * @packageDocumentation
 */

// Company selectors
export {
  selectCompanyState,
  selectCurrentCompany,
  selectCurrentEmployee,
  selectEmployees,
  selectIsB2BActive,
  selectCompanyStatus,
  selectIsCompanyLoading,
  selectCompanyError,
  selectCompanyLastRefreshed,
  selectCurrentCompanyId,
  selectCurrentCompanyName,
  selectCurrentCompanyTier,
  selectCompanyAvailableCredit,
  selectCompanyCreditLimit,
  selectCompanyCreditUsagePercent,
  selectCompanyPaymentTerms,
  selectCompanyAddresses,
  selectDefaultShippingAddressId,
  selectDefaultBillingAddressId,
  selectCurrentEmployeeId,
  selectCurrentEmployeeName,
  selectCurrentEmployeeRole,
  selectCurrentEmployeePermissions,
  selectHasPermission,
  selectIsApprover,
  selectEmployeeApprovalLimit,
  selectEmployeeSpendingLimits,
  selectEmployeeCurrentSpending,
  selectEmployeeById,
  selectApproverEmployees,
  selectEmployeeCount,
  selectCanCreateOrders,
  selectCanCreateQuotes,
  selectCanApproveOrders,
  selectRequiresOrderApproval,
} from "./company.selectors";

// Quotes selectors
export {
  selectQuotesState,
  selectQuotes,
  selectSelectedQuote,
  selectQuoteFilters,
  selectActiveStatusFilter,
  selectQuoteSearchQuery,
  selectQuotesListStatus,
  selectIsQuotesLoading,
  selectQuoteDetailStatus,
  selectIsQuoteDetailLoading,
  selectQuotesError,
  selectQuotesPagination,
  selectQuotesCurrentPage,
  selectQuotesTotalCount,
  selectQuotesHasNextPage,
  selectQuotesHasPreviousPage,
  selectQuoteById,
  selectQuotesByStatus,
  selectFilteredQuotes,
  selectQuoteCountByStatus,
  selectQuotesWithUnreadMessages,
  selectUnreadQuotesCount,
  selectExpiringQuotes,
  selectHasQuotes,
  selectQuotesTotalValue,
  selectSelectedQuoteId,
  selectSelectedQuoteStatus,
  selectSelectedQuoteItems,
  selectSelectedQuoteTotals,
  selectCanAcceptSelectedQuote,
  selectCanEditSelectedQuote,
} from "./quotes.selectors";

// Approvals selectors
export {
  selectApprovalsState,
  selectPendingApprovals,
  selectAllApprovals,
  selectSelectedApproval,
  selectPendingApprovalCount,
  selectApprovalCount,
  selectApprovalFilters,
  selectApprovalStatusFilter,
  selectApprovalsListStatus,
  selectIsApprovalsLoading,
  selectApprovalDetailStatus,
  selectIsApprovalDetailLoading,
  selectApprovalsError,
  selectApprovalsPagination,
  selectApprovalsCurrentPage,
  selectApprovalsTotalCount,
  selectApprovalById,
  selectApprovalsByStatus,
  selectApprovalsByEntityType,
  selectPendingOrderApprovals,
  selectPendingQuoteApprovals,
  selectOverdueApprovals,
  selectOverdueApprovalCount,
  selectHighPriorityApprovals,
  selectHasPendingApprovals,
  selectPendingApprovalsTotalValue,
  selectApprovalCountsByStatus,
  selectSelectedApprovalId,
  selectSelectedApprovalStatus,
  selectSelectedApprovalSteps,
  selectSelectedApprovalCurrentLevel,
  selectCanActionSelectedApproval,
  selectIsSelectedApprovalOverdue,
} from "./approvals.selectors";

// Cart selectors
export {
  selectCartB2BState,
  selectCartItems,
  selectCartItemCount,
  selectCartTotals,
  selectCartTotal,
  selectSpendingValidation,
  selectCanCheckout,
  selectCheckoutBlockedReason,
  selectCartStatus,
  selectIsCartLoading,
  selectCartError,
  selectCartLastUpdated,
  selectCartShippingAddressId,
  selectCartPurchaseOrderNumber,
  selectCartNotes,
  selectCartItemByProductId,
  selectCartItemQuantity,
  selectIsProductInCart,
  selectCartUniqueItemCount,
  selectCartSubtotal,
  selectCartTierDiscount,
  selectCartVolumeDiscount,
  selectCartTotalDiscount,
  selectCartShippingEstimate,
  selectCartTax,
  selectCartCurrency,
  selectIsWithinSpendingLimits,
  selectRequiresApproval,
  selectApprovalReason,
  selectApplicableSpendingLimits,
  selectSpendingWarnings,
  selectHasSpendingWarnings,
  selectIsCartEmpty,
  selectInvalidQuantityItems,
  selectAllQuantitiesValid,
  selectCartTotalQuantity,
  selectAverageItemPrice,
  selectCartForPersistence,
  selectCheckoutSummary,
  type CheckoutSummary,
} from "./cart.selectors";
